### ISSUE TITLE
Make new server release

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/cids-custom-switchon-server#34]
Make a new release of cids-custom-switchon-server and cids-server-rest-legacy on dealtares server for **public beta**.

- Don't forget to copy the updated switchon database to the deltares server. See [Integration Base Instances](https://github.com/switchonproject/cids-custom-switchon/wiki/Integration-Base-Instances). 
- don't forget to copy the GRDC Resource(s) from switchon_dev to switchon and to create the new indexes (see https://github.com/switchonproject/cids-custom-switchon-server/issues/7#issuecomment-77150688)

**Comment by p-a-s-c-a-l** [comment]
Don't forget to update the Wiki: https://github.com/switchonproject/cids-custom-switchon/wiki/SIP-Releases#cids-servers-1

**Comment by p-a-s-c-a-l** [comment]
Enable GZIP compression in cids legacy rest server

**Comment by p-a-s-c-a-l** [comment]
Status: The database switchon@switchon.cismet.de is up to data and should replace switchon@deltares.

**Comment by p-a-s-c-a-l** [comment]
Update the pycsw data table (see [wiki](https://github.com/switchonproject/cids-custom-switchon/wiki/SIP-Releases#pycsw-prototype)) with the [update script](https://github.com/switchonproject/cids-custom-switchon-server/blob/dev/src/model/scripts/csw_copy_data_table_from_view_for_pycsw.sql).

**Comment by mscholl** [comment]
did update of server, however, did not update any configs or pycsw data

**Comment by esafa** [comment]
we are ready to do some user testing... ping us when the latest version is
deployed at portal.


On Mon, Apr 6, 2015 at 8:48 PM, Martin Scholl <notifications@github.com>
wrote:

> did update of server, however, did not update any configs or pycsw data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/cids-custom-switchon-server/issues/34#issuecomment-90194598>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
switchon meta-db on deltares derver updated

**Comment by p-a-s-c-a-l** [comment]
@mscholl New release should be made asap when #36 is resolved.

**Comment by p-a-s-c-a-l** [comment]
done
