### ISSUE TITLE
Import GRDC Stations

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/cids-custom-switchon-server#39]
Import all GRDC Stations as distinct resources to provide a reference for re-purposed GRDC station data.
 >1. for each (or almost each) grdc station we have estimated flood peaks (this mean we have for each station a table with different dates and flood peaks )
2. in a second step - shmi will estimate and assign for those days (when flood peaks occur) some  additional information (they will use a model and simulate soil moisture and some other characteristics for those periods of floods)...so for each station they will provide some new additional metainfo for some of the stations again...
3. in the next steps, we plan also to use sip and some other datasets to derive some additional information again for each station (related to those flood peaks), like weather circulation pattern, presipitation amount, etc.

See also https://github.com/switchonproject/sip-html5/issues/46

**Comment by p-a-s-c-a-l** [comment]
waiting for https://github.com/switchonproject/sip-html5/issues/103

**Comment by esafa** [comment]
Ill go to the lawyer tomorrow.

On Mon, Jul 6, 2015 at 10:45 AM, Pascal Dihé <notifications@github.com>
wrote:

> waiting for switchonproject/sip-html5#103
> <https://github.com/switchonproject/sip-html5/issues/103>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/cids-custom-switchon-server/issues/39#issuecomment-118776711>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)
