### ISSUE TITLE
Derive spatial extent from uploaded files

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/cids-custom-switchon-server#55]
Derive the spatial extent of resources from uploaded Shape Files (or other spatial data): Extract polygons from spatial data files, simplify and consolidate polygons, import polygons into dedicated spatial search index of the Meta-Data Repository (shell scripts, GDAL command line tools) 
and create link between spatial index and previously registered resource meta-data.

- implement new server action
- update SearchGeomTrigger

**Comment by esafa** [comment]
this is something the summerworkers may help with..

fredag 20 maj 2016 skrev Pascal Dihé <notifications@github.com>:

> Derive the spatial extent of resources from uploaded Shape Files (or other
> spatial data): Extract polygons from spatial data files, simplify and
> consolidate polygons, import polygons into dedicated spatial search index
> of the Meta-Data Repository (shell scripts, GDAL command line tools)
> and create link between spatial index and previously registered resource
> meta-data.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/cids-custom-switchon-server/issues/55>
>


-- 
Esa Falkenroth
mobile: 0702-10 40 28 intl +46702104028
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
[Processing Instructions Documentation](https://github.com/switchonproject/cids-custom-switchon-server/wiki/Processing-Instructions)

**Comment by esafa** [comment]
Thanks. Instructions seem clear enough.
//Esa

tisdag 24 maj 2016 skrev Pascal Dihé <notifications@github.com>:

> Processing Instructions Documentation
> <https://github.com/switchonproject/cids-custom-switchon-server/wiki/Processing-Instructions>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/cids-custom-switchon-server/issues/55#issuecomment-221325722>
>


-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
if SHP filename starts with integer, OGR2OGR fails with:
``ERROR 1: SQL Expression Parsing Error: syntax error, unexpected integer number, expecting string or identifier. Occured around :
SELECT FID FROM 20141218_GRDC_Stations``

**Comment by p-a-s-c-a-l** [comment]
done
